FROM node:16 AS build
WORKDIR /app
COPY package*.json ./
ARG REACT_APP_SERVIDOR
ARG REACT_APP_BASE
ENV REACT_APP_SERVIDOR=$REACT_APP_SERVIDOR
ENV REACT_APP_BASE=$REACT_APP_BASE
RUN npm install
COPY . .
RUN npm run build

FROM nginx:alpine
COPY --from=build /app/build/ /usr/share/nginx/html/
COPY nginx/default.conf /etc/nginx/conf.d/default.conf  
EXPOSE 80