version: "3.8"

services:
  frontend:
    build:
      context: ./client
    env_file: ./client/.env.production
    networks: [app-network]

  backend:
    build:
      context: ./server
    env_file: ./server/.env.production
    environment:
      - PORT=3001          
    depends_on: [mongo]
    networks: [app-network]

  mongo:
    image: mongo
    ports:
      - "27017:27017"      
    volumes:
      - ./mongo-data:/data/db
    networks: [app-network]

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./client/build:/usr/share/nginx/html:ro
    depends_on: [backend, frontend]
    networks: [app-network]


networks:
  app-network:
    driver: bridge
