version: '3.8'          

services:
  frontend:
    build:
      context: ./client
    env_file: ./client/.env.production
    networks:
      - app-network

  backend:
    build:
      context: ./server
    env_file: ./server/.env.production
    networks:
      - app-network
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db        
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
