version: '3'

services:
  frontend:
    build:
      context: ./client
    ports:
      - "80:80"
    networks:
      - app-network

  backend:
    build:
      context: ./server
    ports:
      - "3001:3001"
    networks:
      - app-network
    environment:
      - MONGO_URI=mongodb://mongo:27017/yourdb
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
