version: '3'

services:
  build: { context: ./client }
    env_file: ./client/.env.production
    ports: [ "80:80" ]
    networks: [ app-network ]

  backend:
    build: { context: ./server }
    env_file: ./server/.env.production
    ports: [ "3001:3001" ]
    networks: [ app-network ]
    depends_on: [ mongo ]

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
