version: "3.8"

services:
  frontend:
    build:
      context: ./client
      args:
        REACT_APP_SERVIDOR: http://backend:3001
        REACT_APP_BASE: http://92.113.34.107
    depends_on:
      - backend
      - mongo
    networks: [app-network]
    ports:
      - "80:80"

  backend:
    build:
      context: ./server
    env_file: ./server/.env.production
    environment:
      - PORT=3001
    ports:
      - "3001:3001"
    volumes:
      - ./server/public/projects:/app/public/projects
      - ./server/uploads:/app/uploads
      - ./client/build:/client/build
    depends_on:
      - mongo
    networks: [app-network]

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-data:/data/db
    networks:
      - app-network

  museu_virtual_manhuacu:
    build:
      context: ./server/public/projects/project_museuvirtual_tremvirtual_1753663884349
    ports:
      - "8080:8080"
    networks: [app-network]
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
