name: Deploy to Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.7
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          cd /home/matheus/tremvirtual
          git pull origin master
          
          cd /home/matheus/tremvirtual/client
          npm install --legacy-peer-deps
          npm run build
          
          sudo rm -rf /usr/share/nginx/html
          sudo cp -r /home/matheus/tremvirtual/client/build /usr/share/nginx/html
          
          cd /home/matheus/tremvirtual
          docker-compose down
          docker-compose up -d --build
